# Site settings
title: Reasoning with Quantifiers
email: ""
description: "Primer on web experiments for Chris Potts &amp; Dan Lassiter's seminar 'Reasoning with Quantifiers' (Linguistics 236), Stanford, Winter 2015"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://danlassiter.github.io/" # the base hostname & protocol for your site
twitter_username: "danlassiter"
github_username:  "danlassiter"

# Build settings
markdown: kramdown
highlighter: pygments